FROM openjdk:8

# sqlite
RUN apt-get -y update \
  && apt-get -y upgrade \
  && apt-get install -y sqlite3 libsqlite3-dev \
  && mkdir /db \
  && /usr/bin/sqlite3 /db/kubeiaas.db

ADD ./target/db-proxy-0.1.1-SNAPSHOT.jar /root/db-proxy.jar
