FROM nginx:latest

RUN mkdir -p /workdir/
COPY iaas-vue.tar.gz /workdir

# docker build -t registry.cn-beijing.aliyuncs.com/kubeiaas/front-nginx:1.1.0-SNAPSHOT .
# docker push registry.cn-beijing.aliyuncs.com/kubeiaas/front-nginx:1.1.0-SNAPSHOT