---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iaas-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iaas-core
  template:
    metadata:
      labels:
        app: iaas-core
    spec:
      containers:
        - name: iaas-core
          command: ["sh"]
          args:
            - "-c"
            - |
              java -jar /root/iaas-core-0.0.1-SNAPSHOT.jar
          image: registry.cn-beijing.aliyuncs.com/kubeiaas/iaas-core:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
              hostPort: 9080
              protocol: TCP
          env:
            - name: DHCP_HOST_IP
              value: "192.168.31.238"
            - name: VNC_HOST_IP
              value: "192.168.31.238"
---
apiVersion: v1
kind: Service
metadata:
  name: iaas-core
spec:
  selector:
    app: iaas-core
  type: ClusterIP
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
