FROM free4inno/java-jdk8

RUN mkdir -p /workdir/
COPY iaas-front.war /workdir

# docker build -t registry.cn-beijing.aliyuncs.com/kubeiaas/front-web:1.0-RELEASE .
# docker push registry.cn-beijing.aliyuncs.com/kubeiaas/front-web:1.0-RELEASE