---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iaas-agent
  namespace: kubeiaas
spec:
  selector:
    matchLabels:
      app: iaas-agent
  template:
    metadata:
      labels:
        app: iaas-agent
    spec:
      # 打标签：kubectl label node hf-node-01 kubeiaas/node=true
      nodeSelector:
        kubeiaas/node: "true"   # 指定节点标签
      hostPID: true
      hostIPC: true
      containers:
        - name: iaas-agent
          command: ["sh"]
          args:
            - "-c"
            - |
              /bin/bash /kubeiaas/RUN.sh
          image: registry.cn-beijing.aliyuncs.com/kubeiaas/iaas-agent:0.1.1-SNAPSHOT
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - containerPort: 9090
              hostPort: 9090
              protocol: TCP
            - containerPort: 9089
#              hostPort: 9089
              protocol: TCP
          env:
            # -------- BASIC ENV --------
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # -------- SERVICE CONFIG --------
            - name: DHCP_NODE
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.dhcp
            - name: VNC_NODE
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.vnc
            - name: NFS_NODE
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.nfs
            # -------- NETWORK CONFIG --------
            - name: NETWORK_BRIDGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: network.bridge.type
            # ----------------------------------
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
            - name: workdir
              mountPath: /workdir
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
        - name: workdir
          hostPath:
            path: /usr/local/kubeiaas/workdir
---
apiVersion: v1
kind: Service
metadata:
  name: iaas-agent
  namespace: kubeiaas
spec:
  selector:
    app: iaas-agent
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP