---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-operator
  namespace: kubeiaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-operator
  template:
    metadata:
      labels:
        app: resource-operator
    spec:
      containers:
        - name: resource-operator
          command: ["sh"]
          args:
            - "-c"
            - |
              java -jar /root/resource-operator.jar
          image: registry.cn-beijing.aliyuncs.com/kubeiaas/resource-operator:0.1.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: resource-operator
  namespace: kubeiaas
spec:
  selector:
    app: resource-operator
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
